### PR TITLE
Replace subkey with go port

### LINKED ISSUE #112: Replace subkey with go-subkey port
Have you considered moving to [go-subkey port](https://github.com/vedhavyas/go-subkey) so that installing subkey is not needed? I see this port is made by @vedhavyas

I have replaced it on [this fork](https://github.com/NodeFactoryIo/go-substrate-rpc-client) and everything seems to be working as intended.

### PR DESCRIPTION
**Pull request by MakMuftic**
I replaced calling `subkey` with _go-subkey port_ as I mentioned in #112 

closes #112

### CODE REVIEW

**Review by vedhavyas — APPROVED** [review]
Thanks! @MakMuftic 

LGTM!

**Comment by MakMuftic** [comment]
@vedhavyas Great :partying_face: 

When could I expect this to be released, as I would like to move away from our custom fork and use your client?

**Review by mikiquantum — APPROVED** [review]
LGTM @MakMuftic , thanks!

**Comment by mikiquantum** [comment]
@MakMuftic @vedhavyas Merging now, will release as well.

**Pull request merged**
