### PR TITLE
CreateStorageKey improvements + Comprehensive tests

### PR DESCRIPTION
**Pull request by ParthDesai**
# What is changed?
- Comprehensive tests for `CreateStorageKey`
- Remove unreachable code in `Hashers` function
- Improve `CreateStorageKey` error handling

### CODE REVIEW

**Comment by ParthDesai** [comment]
@vedhavyas This will improve library user's confidence in `CreateStorageKey` as well as serve as a guide on how to invoke `CreateStorageKey`

**Review by vedhavyas — APPROVED** [review]
LGTM Thanks!

**Comment by vedhavyas** [comment]
@ParthDesai I would wait for the issue reporter to confirm the fix then merge and release a patch.

**Comment by ParthDesai** [comment]
> @ParthDesai I would wait for the issue reporter to confirm the fix then merge and release a patch.

@vedhavyas The regression was already fixed via PR: #166
But, it was not covered by tests. PR: #169 aims to cover the new changes made in CreateStorageKey with tests.

**Pull request merged**
