### PR TITLE
Add dynamic extrinsic signing support

### PR DESCRIPTION
**Pull request by cdamian**
The changes in this PR add a new type of extrinsic that can have a dynamic payload and signature, based on the information in the metadata.

Test script can be found [here](https://gist.github.com/cdamian/0f329ae74f5c0ef5fae5e9cef0ca8cec).

### CODE REVIEW

**Comment by henrikdent** [comment]
Could you consider adding a version of `SubmitExtrinsic` that accepts a `extrinsic.DynamicExtrinsic` as well?

**Comment by cdamian** [comment]
@henrikdent I think the final version will be a breaking change where we completely drop support for the old version, we have not decided yet since we still have to test this with other chains such as AssetHub.

**Comment by akme** [comment]
Tried to use this branch, but get an error:
```
panic: creating payload: signed extension 'StorageWeightReclaim' is not supported
```
while doing this:
```
	err = ext.Sign(
		keyPair,
		meta,
		extrinsic.WithEra(types.ExtrinsicEra{IsImmortalEra: true}, genesisHash),
		extrinsic.WithNonce(types.NewUCompactFromUInt(uint64(accountInfo.Nonce))),
		extrinsic.WithTip(types.NewUCompactFromUInt(0)),
		extrinsic.WithSpecVersion(rv.SpecVersion),
		extrinsic.WithTransactionVersion(rv.TransactionVersion),
		extrinsic.WithGenesisHash(genesisHash),
		extrinsic.WithMetadataMode(extensions.CheckMetadataModeDisabled, extensions.CheckMetadataHash{Hash: types.NewEmptyOption[types.H256]()}),
	)
```

**Comment by cdamian** [comment]
> Tried to use this branch, but get an error:
> 
> ```
> panic: creating payload: signed extension 'StorageWeightReclaim' is not supported
> ```
> 
> while doing this:
> 
> ```
> 	err = ext.Sign(
> 		keyPair,
> 		meta,
> 		extrinsic.WithEra(types.ExtrinsicEra{IsImmortalEra: true}, genesisHash),
> 		extrinsic.WithNonce(types.NewUCompactFromUInt(uint64(accountInfo.Nonce))),
> 		extrinsic.WithTip(types.NewUCompactFromUInt(0)),
> 		extrinsic.WithSpecVersion(rv.SpecVersion),
> 		extrinsic.WithTransactionVersion(rv.TransactionVersion),
> 		extrinsic.WithGenesisHash(genesisHash),
> 		extrinsic.WithMetadataMode(extensions.CheckMetadataModeDisabled, extensions.CheckMetadataHash{Hash: types.NewEmptyOption[types.H256]()}),
> 	)
> ```

@akme we were not aware of that signing extension, can you please let us know what chain this is so we can look into it?

**Comment by akme** [comment]
> @akme we were not aware of that signing extension, can you please let us know what chain this is so we can look into it?

It happens with `wss://rococo-asset-hub-rpc.polkadot.io` when I try to sign this `types.NewCall(meta, "Assets.transfer", assetIdSerialized, bob, types.NewU128(*bal))`

**Comment by cdamian** [comment]
@akme added another signing option `WithAssetID` that you should add when signing the extrinsic.

I tested it successfully using a simple remark call on the chain that you mentioned.

In a modified version of the above mentioned test script I added:

```
...

err = ext.Sign(
		BobKeyRingPair,
		meta,
		extrinsic.WithEra(types.ExtrinsicEra{IsImmortalEra: true}, genesisHash),
		extrinsic.WithNonce(types.NewUCompactFromUInt(uint64(accountInfo.Nonce))),
		extrinsic.WithTip(types.NewUCompactFromUInt(0)),
		extrinsic.WithSpecVersion(rv.SpecVersion),
		extrinsic.WithTransactionVersion(rv.TransactionVersion),
		extrinsic.WithGenesisHash(genesisHash),
		extrinsic.WithMetadataMode(extensions.CheckMetadataModeDisabled, extensions.CheckMetadataHash{Hash: types.NewEmptyOption[types.H256]()}),
		extrinsic.WithAssetID(types.NewEmptyOption[types.AssetID]()),
	)
	
...
```

Please let me know if you encounter any issues.

**Comment by liuguangmao** [comment]
It can't work either


> @akme added another signing option `WithAssetID` that you should add when signing the extrinsic.
> 
> I tested it successfully using a simple remark call on the chain that you mentioned.
> 
> In a modified version of the above mentioned test script I added:
> 
> ```
> ...
> 
> err = ext.Sign(
> 		BobKeyRingPair,
> 		meta,
> 		extrinsic.WithEra(types.ExtrinsicEra{IsImmortalEra: true}, genesisHash),
> 		extrinsic.WithNonce(types.NewUCompactFromUInt(uint64(accountInfo.Nonce))),
> 		extrinsic.WithTip(types.NewUCompactFromUInt(0)),
> 		extrinsic.WithSpecVersion(rv.SpecVersion),
> 		extrinsic.WithTransactionVersion(rv.TransactionVersion),
> 		extrinsic.WithGenesisHash(genesisHash),
> 		extrinsic.WithMetadataMode(extensions.CheckMetadataModeDisabled, extensions.CheckMetadataHash{Hash: types.NewEmptyOption[types.H256]()}),
> 		extrinsic.WithAssetID(types.NewEmptyOption[types.AssetID]()),
> 	)
> 	
> ...
> ```
> 
> Please let me know if you encounter any issues.

**Comment by akme** [comment]
> Please let me know if you encounter any issues.

It worked for `Balances.transfer_keep_alive`, I was able to send ROC between accounts.
It didn't work for `Assets.transfer`:
```
Ext - 0x8102840066f34a40ef3d840e5354e1c7c3362179ab03d286d8ad10ec54fbaab1a4de415401348c8e5412b800d3ac62152676a43a75efebeb08c1bb3aa4223b293ac7fa6f126ac1c9f15b9ff0262002c74fb1d682d6bebb7eafb0352952016303cf03c8158c0018000000320810890000000011928a7729d09635de0b8a9d8e0e528aa910b00057e1cffa1ca6b9e3e279125f10270000000000000000000000000000
panic: Verification Error: Runtime error: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
WASM backtrace:
error while executing at wasm backtrace:
    0: 0x4f79d7 - <unknown>!rust_begin_unwind
    1: 0x4a9f17 - <unknown>!core::panicking::panic_fmt::h7d22643b0becf577
    2: 0x1b11b0 - <unknown>!TaggedTransactionQueue_validate_transaction
```
should I pass an assetId here `extrinsic.WithAssetID(types.NewEmptyOption[types.AssetID]())`?
another question is how to get a hash/txid of extrinsic?

**Comment by liuguangmao** [comment]
Would you create a gist about test `Balances.transfer_keep_alive` ?
Mine get the same error on this method.
Thank you so much.

> extrinsic.WithEra(types.ExtrinsicEra{IsImmortalEra: true}, genesisHash),
> 		extrinsic.WithNonce(types.NewUCompactFromUInt(uint64(accountInfo.Nonce))),
> 		extrinsic.WithTip(types.NewUCompactFromUInt(0)),
> 		extrinsic.WithSpecVersion(rv.SpecVersion),
> 		extrinsic.WithTransactionVersion(rv.TransactionVersion),
> 		extrinsic.WithGenesisHash(genesisHash),
> 		extrinsic.WithMetadataMode(extensions.CheckMetadataModeDisabled, extensions.CheckMetadataHash{Hash: types.NewEmptyOption[types.H256]()}),
> 		extrinsic.WithAssetID(types.NewEmptyOption[types.AssetID]()),

**Comment by liuguangmao** [comment]
Would you create a gist about test Balances.transfer_keep_alive ?
Mine get the same error on this method.
Thank you so much.


> > Please let me know if you encounter any issues.
> 
> It worked for `Balances.transfer_keep_alive`, I was able to send ROC between accounts. It didn't work for `Assets.transfer`:
> 
> ```
> Ext - 0x8102840066f34a40ef3d840e5354e1c7c3362179ab03d286d8ad10ec54fbaab1a4de415401348c8e5412b800d3ac62152676a43a75efebeb08c1bb3aa4223b293ac7fa6f126ac1c9f15b9ff0262002c74fb1d682d6bebb7eafb0352952016303cf03c8158c0018000000320810890000000011928a7729d09635de0b8a9d8e0e528aa910b00057e1cffa1ca6b9e3e279125f10270000000000000000000000000000
> panic: Verification Error: Runtime error: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
> WASM backtrace:
> error while executing at wasm backtrace:
>     0: 0x4f79d7 - <unknown>!rust_begin_unwind
>     1: 0x4a9f17 - <unknown>!core::panicking::panic_fmt::h7d22643b0becf577
>     2: 0x1b11b0 - <unknown>!TaggedTransactionQueue_validate_transaction
> ```
> 
> should I pass an assetId here `extrinsic.WithAssetID(types.NewEmptyOption[types.AssetID]())`? another question is how to get a hash/txid of extrinsic?



> > Please let me know if you encounter any issues.
> 
> It worked for `Balances.transfer_keep_alive`, I was able to send ROC between accounts. It didn't work for `Assets.transfer`:
> 
> ```
> Ext - 0x8102840066f34a40ef3d840e5354e1c7c3362179ab03d286d8ad10ec54fbaab1a4de415401348c8e5412b800d3ac62152676a43a75efebeb08c1bb3aa4223b293ac7fa6f126ac1c9f15b9ff0262002c74fb1d682d6bebb7eafb0352952016303cf03c8158c0018000000320810890000000011928a7729d09635de0b8a9d8e0e528aa910b00057e1cffa1ca6b9e3e279125f10270000000000000000000000000000
> panic: Verification Error: Runtime error: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
> WASM backtrace:
> error while executing at wasm backtrace:
>     0: 0x4f79d7 - <unknown>!rust_begin_unwind
>     1: 0x4a9f17 - <unknown>!core::panicking::panic_fmt::h7d22643b0becf577
>     2: 0x1b11b0 - <unknown>!TaggedTransactionQueue_validate_transaction
> ```
> 
> should I pass an assetId here `extrinsic.WithAssetID(types.NewEmptyOption[types.AssetID]())`? another question is how to get a hash/txid of extrinsic?

**Comment by akme** [comment]
> Would you create a gist about test Balances.transfer_keep_alive ? Mine get the same error on this method. Thank you so much.
```
func Example_makeASimpleTransfer(keyPair signature.KeyringPair) {
	// This sample shows how to create a transaction to make a transfer from one an account to another.

	// Instantiate the API
	api, err := gsrpc.NewSubstrateAPI("wss://rococo-asset-hub-rpc.polkadot.io")
	if err != nil {
		panic(err)
	}

	meta, err := api.RPC.State.GetMetadataLatest()
	if err != nil {
		panic(err)
	}

	// Create a call, transferring 12345 units to Bob
	bob, err := types.NewMultiAddressFromHexAccountID("0x8eaf04151687736326c9fea17e25fc5287613693c912909cb226aa4794f26a48")
	if err != nil {
		panic(err)
	}

	// 1 unit of transfer
	bal, ok := new(big.Int).SetString("1000000000000", 10)
	if !ok {
		panic(fmt.Errorf("failed to convert balance"))
	}

	c, err := types.NewCall(meta, "Balances.transfer_keep_alive", bob, types.NewUCompact(bal))
	if err != nil {
		panic(err)
	}

	ext := extrinsic.NewDynamicExtrinsic(&c)

	genesisHash, err := api.RPC.Chain.GetBlockHash(0)
	if err != nil {
		panic(err)
	}

	rv, err := api.RPC.State.GetRuntimeVersionLatest()
	if err != nil {
		panic(err)
	}

	key, err := types.CreateStorageKey(meta, "System", "Account", keyPair.PublicKey)
	if err != nil {
		panic(err)
	}

	var accountInfo types.AccountInfo
	ok, err = api.RPC.State.GetStorageLatest(key, &accountInfo)
	if err != nil || !ok {
		panic(err)
	}

	err = ext.Sign(
		keyPair,
		meta,
		extrinsic.WithEra(types.ExtrinsicEra{IsImmortalEra: true}, genesisHash),
		extrinsic.WithNonce(types.NewUCompactFromUInt(uint64(accountInfo.Nonce))),
		extrinsic.WithTip(types.NewUCompactFromUInt(0)),
		extrinsic.WithSpecVersion(rv.SpecVersion),
		extrinsic.WithTransactionVersion(rv.TransactionVersion),
		extrinsic.WithGenesisHash(genesisHash),
		extrinsic.WithMetadataMode(extensions.CheckMetadataModeDisabled, extensions.CheckMetadataHash{Hash: types.NewEmptyOption[types.H256]()}),
		extrinsic.WithAssetID(types.NewEmptyOption[types.AssetID]()),
	)

	if err != nil {
		panic(err)
	}



	encodedExt, err := codec.EncodeToHex(ext)
	if err != nil {
		panic(err)
	}
	fmt.Printf("Ext - %s\n", encodedExt)

	sub, err := api.RPC.Author.SubmitAndWatchDynamicExtrinsic(ext)
	if err != nil {
		panic(err)
	}
	defer sub.Unsubscribe()

	for {
		select {
		case st := <-sub.Chan():
			extStatus, _ := st.MarshalJSON()
			fmt.Printf("Status for transaction - %s\n", string(extStatus))
		case err := <-sub.Err():
			panic(err)
		}
	}
}
```
Keep in mind that your go.mod should point to the commit from this branch `feature/add-dynamic-extrinsic-signing-support`.
I've just added this line at the end of my `go.mod` file and made `go mod tidy`:
```
replace github.com/centrifuge/go-substrate-rpc-client/v4 => github.com/centrifuge/go-substrate-rpc-client/v4 v4.2.1-0.20240711233432-c7949e1f6b9a
```

**Comment by hugeroot001** [comment]
Your code  works for `Balances.transfer_allow_death`  on westend.
Westend metadata don't have  `Assets.transfer` .
I'll check the difference between your and mine .
Thank you very much






> > Would you create a gist about test Balances.transfer_keep_alive ? Mine get the same error on this method. Thank you so much.
> 
> ```
> func Example_makeASimpleTransfer(keyPair signature.KeyringPair) {
> 	// This sample shows how to create a transaction to make a transfer from one an account to another.
> 
> 	// Instantiate the API
> 	api, err := gsrpc.NewSubstrateAPI("wss://rococo-asset-hub-rpc.polkadot.io")
> 	if err != nil {
> 		panic(err)
> 	}
> 
> 	meta, err := api.RPC.State.GetMetadataLatest()
> 	if err != nil {
> 		panic(err)
> 	}
> 
> 	// Create a call, transferring 12345 units to Bob
> 	bob, err := types.NewMultiAddressFromHexAccountID("0x8eaf04151687736326c9fea17e25fc5287613693c912909cb226aa4794f26a48")
> 	if err != nil {
> 		panic(err)
> 	}
> 
> 	// 1 unit of transfer
> 	bal, ok := new(big.Int).SetString("1000000000000", 10)
> 	if !ok {
> 		panic(fmt.Errorf("failed to convert balance"))
> 	}
> 
> 	c, err := types.NewCall(meta, "Balances.transfer_keep_alive", bob, types.NewUCompact(bal))
> 	if err != nil {
> 		panic(err)
> 	}
> 
> 	ext := extrinsic.NewDynamicExtrinsic(&c)
> 
> 	genesisHash, err := api.RPC.Chain.GetBlockHash(0)
> 	if err != nil {
> 		panic(err)
> 	}
> 
> 	rv, err := api.RPC.State.GetRuntimeVersionLatest()
> 	if err != nil {
> 		panic(err)
> 	}
> 
> 	key, err := types.CreateStorageKey(meta, "System", "Account", keyPair.PublicKey)
> 	if err != nil {
> 		panic(err)
> 	}
> 
> 	var accountInfo types.AccountInfo
> 	ok, err = api.RPC.State.GetStorageLatest(key, &accountInfo)
> 	if err != nil || !ok {
> 		panic(err)
> 	}
> 
> 	err = ext.Sign(
> 		keyPair,
> 		meta,
> 		extrinsic.WithEra(types.ExtrinsicEra{IsImmortalEra: true}, genesisHash),
> 		extrinsic.WithNonce(types.NewUCompactFromUInt(uint64(accountInfo.Nonce))),
> 		extrinsic.WithTip(types.NewUCompactFromUInt(0)),
> 		extrinsic.WithSpecVersion(rv.SpecVersion),
> 		extrinsic.WithTransactionVersion(rv.TransactionVersion),
> 		extrinsic.WithGenesisHash(genesisHash),
> 		extrinsic.WithMetadataMode(extensions.CheckMetadataModeDisabled, extensions.CheckMetadataHash{Hash: types.NewEmptyOption[types.H256]()}),
> 		extrinsic.WithAssetID(types.NewEmptyOption[types.AssetID]()),
> 	)
> 
> 	if err != nil {
> 		panic(err)
> 	}
> 
> 
> 
> 	encodedExt, err := codec.EncodeToHex(ext)
> 	if err != nil {
> 		panic(err)
> 	}
> 	fmt.Printf("Ext - %s\n", encodedExt)
> 
> 	sub, err := api.RPC.Author.SubmitAndWatchDynamicExtrinsic(ext)
> 	if err != nil {
> 		panic(err)
> 	}
> 	defer sub.Unsubscribe()
> 
> 	for {
> 		select {
> 		case st := <-sub.Chan():
> 			extStatus, _ := st.MarshalJSON()
> 			fmt.Printf("Status for transaction - %s\n", string(extStatus))
> 		case err := <-sub.Err():
> 			panic(err)
> 		}
> 	}
> }
> ```
> 
> Keep in mind that your go.mod should point to the commit from this branch `feature/add-dynamic-extrinsic-signing-support`. I've just added this line at the end of my `go.mod` file and made `go mod tidy`:
> 
> ```
> replace github.com/centrifuge/go-substrate-rpc-client/v4 => github.com/centrifuge/go-substrate-rpc-client/v4 v4.2.1-0.20240711233432-c7949e1f6b9a
> ```

**Comment by cdamian** [comment]
@akme you can find a gist for executing the `Assets.transfer` call [here](https://gist.github.com/cdamian/078bf981c8e333b03747eb2046e92cbd).

You can also get a signed extrinsic from - https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo-asset-hub-rpc.polkadot.io#/extrinsics by selecting the extrinsic that you want, adding the arguments to the call, go to "Submit Transaction", disable "sign and submit", set lifetime to 0, hit "Sign (no submission)". You will then get an encoded signed extrinsic. This is what I usually do when debugging these kind of issues.

**Comment by akme** [comment]
> @akme you can find a gist for executing the `Assets.transfer` call [here](https://gist.github.com/cdamian/078bf981c8e333b03747eb2046e92cbd).
Awesome, your gist worked! Thank you!

> You can also get a signed extrinsic from - https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo-asset-hub-rpc.polkadot.io#/extrinsics by selecting the extrinsic that you want, adding the arguments to the call, go to "Submit Transaction", disable "sign and submit", set lifetime to 0, hit "Sign (no submission)". You will then get an encoded signed extrinsic. This is what I usually do when debugging these kind of issues.
Thanks for the info!

Could you please help me to understand a way to get an ID of extrinsic that I send with the help of your gist? I need to sign and send, then watch for exact extrinsic and create an url, e.g. for an explorer.

**Comment by cdamian** [comment]
> Could you please help me to understand a way to get an ID of extrinsic that I send with the help of your gist? I need to sign and send, then watch for exact extrinsic and create an url, e.g. for an explorer.

@akme not sure I understand your request, but feel free to open a different issue with more details though.

**Comment by akme** [comment]
> @akme not sure I understand your request, but feel free to open a different issue with more details though.

Sure, thanks :)

**Comment by wooyeeyii** [comment]
Another new SignedExtension "PrevalidateAttests" in v1.2.6 for polkadot
```
extrinsic: {
        type: 858
        version: 4
        signedExtensions: [
          {
            identifier: CheckNonZeroSender
            type: 860
            additionalSigned: 35
          }
          {
            identifier: CheckSpecVersion
            type: 861
            additionalSigned: 4
          }
          {
            identifier: CheckTxVersion
            type: 862
            additionalSigned: 4
          }
          {
            identifier: CheckGenesis
            type: 863
            additionalSigned: 12
          }
          {
            identifier: CheckMortality
            type: 864
            additionalSigned: 12
          }
          {
            identifier: CheckNonce
            type: 866
            additionalSigned: 35
          }
          {
            identifier: CheckWeight
            type: 867
            additionalSigned: 35
          }
          {
            identifier: ChargeTransactionPayment
            type: 868
            additionalSigned: 35
          }
          {
            identifier: PrevalidateAttests
            type: 869
            additionalSigned: 35
          }
          {
            identifier: CheckMetadataHash
            type: 870
            additionalSigned: 33
          }
        ]
      }
```

**Comment by cdamian** [comment]
> Polkadot need SignedExtensionName `PrevalidateAttests`

I am looking into this now and will post an update as soon as I have it.

**Comment by cdamian** [comment]
> Polkadot need SignedExtensionName `PrevalidateAttests`

Please try again using the latest version here.

**Comment by kartikaysaxena** [comment]
Hey @cdamian I am using the method "NetworkMembership.nominate" in creating a NewCall for a custom polkadot chain and it is throwing `panic: creating payload: signed extension 'CheckNetworkMembership' is not supported`, can you help me with this out in this as I think this PR could also dynamic support to custom call methods. Thanks!

**Comment by cdamian** [comment]
> Hey @cdamian I am using the method "NetworkMembership.nominate" in creating a NewCall for a custom polkadot chain and it is throwing `panic: creating payload: signed extension 'CheckNetworkMembership' is not supported`, can you help me with this out in this as I think this PR could also help with dynamic support to custom call methods. Thanks!

@kartikaysaxena Hey, can you please tell me what chain this is so I can check?

**Comment by kartikaysaxena** [comment]
> > Hey @cdamian I am using the method "NetworkMembership.nominate" in creating a NewCall for a custom polkadot chain and it is throwing `panic: creating payload: signed extension 'CheckNetworkMembership' is not supported`, can you help me with this out in this as I think this PR could also help with dynamic support to custom call methods. Thanks!
> 
> @kartikaysaxena Hey, can you please tell me what chain this is so I can check?

https://github.com/dhiway/cord

**Comment by cdamian** [comment]
@kartikaysaxena is there a websocket address that I can use in the polkadot JS app, such as - https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpolkadot.api.onfinality.io%2Fpublic-ws#/explorer?

**Comment by kartikaysaxena** [comment]
Here it is @cdamian wss://sparknet.cord.network/

**Comment by cdamian** [comment]
Hi @kartikaysaxena , according to the signed extra found [here](https://github.com/dhiway/cord/blob/develop/pallets/network-membership/src/lib.rs#L401), there are no additional fields required in the payload or signature. Please test using the latest version here and let me know if you encounter any issues. 

I will try to test this locally using the guide found on the github repo you provided earlier.

**Comment by cdamian** [comment]
@kartikaysaxena This [gist](https://gist.github.com/cdamian/5107eb52feb03ed13dd474d219eb8163) is what I used when testing this, with a local docker container:

```
docker run -d -p 9944:9944 -p 30333:30333 -p 9933:9933 -p 9615:9615 -v cord:/tmp/data dhiway/cord:develop --dev --rpc-external --rpc-cors all
```

Please note that the `NetworkMembership.nominate` call you're trying to make takes 2 arguments, as per the extrinsic found [here](https://polkadot-dotapps-io.ipns.dweb.link/?rpc=wss%3A%2F%2Fsparknet.cord.network%2F#/extrinsics).

Wrapping the call in `sudo` seems OK, we did something similar for batches [here](https://github.com/centrifuge/pod/blob/main/pallets/utility/api.go).

**Comment by kartikaysaxena** [comment]
@cdamian 
Got it, just a silly question, how can I pass the params? It is throwing the same error while passing it in "call, err := types.NewCall(meta, "NetworkMembership.nominate", account.Address, types.NewBool(expires))", also yes it seems like the `sudo` isn't any problem

**Comment by kartikaysaxena** [comment]
Thank you very much @cdamian! It now works.

**Comment by freddyli7** [comment]
hey @cdamian, I've encountered the `CheckMetadataHash` issue as well and following all the conversations till here, just want to know what is the current status of the fix? as I tried the latest commit of `feature/add-dynamic-extrinsic-signing-support` branch and still got the same error. Thank you 🙏

**Comment by cdamian** [comment]
@freddyli7 can you please share a URI for this chain so we can test this?

**Comment by freddyli7** [comment]
> @freddyli7 can you please share a URI for this chain so we can test this?

of course, this is the RPC endpoint: `wss://testnet-rpc.tangle.tools`

**Comment by freddyli7** [comment]
hey @cdamian, any updates

**Comment by cdamian** [comment]
@freddyli7 unfortunately not, we are preparing for an audit at the moment and won't have much time to tackle this in the coming days. You can check the required signed information for the chain in question by following the instructions [here](https://github.com/centrifuge/go-substrate-rpc-client/pull/389#issuecomment-2225398135), and compare those with the ones provided by your code.

**Comment by freddyli7** [comment]
> @freddyli7 can you adapt the test script from the PR description, found [here](https://gist.github.com/cdamian/0f329ae74f5c0ef5fae5e9cef0ca8cec), to use the `wss://testnet-rpc.tangle.tools` endpoint and use a different account to sign the extrinsic? The extensions provided there should work. I would do this myself but I don't have a valid account for that testnet nor do I know how to create one.

thank you @cdamian! it works for my chain now, as I didn't realize that there is new type of `DynamicExtrinsic` implemented so I was still using `Extrinsic` and that is why it didn't work. 

Do you have any ETA on finalizing this PR and cut for a proper release?

**Comment by cdamian** [comment]
> > @freddyli7 can you adapt the test script from the PR description, found [here](https://gist.github.com/cdamian/0f329ae74f5c0ef5fae5e9cef0ca8cec), to use the `wss://testnet-rpc.tangle.tools` endpoint and use a different account to sign the extrinsic? The extensions provided there should work. I would do this myself but I don't have a valid account for that testnet nor do I know how to create one.
> 
> thank you @cdamian! it works for my chain now, as I didn't realize that there is new type of `DynamicExtrinsic` implemented so I was still using `Extrinsic` and that is why it didn't work.
> 
> Do you have any ETA on finalizing this PR and cut for a proper release?

Will start tackling this now and hopefully get this in no later than end of next week.

**Comment by freddyli7** [comment]
hey @cdamian another quick question, as I'm testing my chain for the event parsing after the extrinsic got executed, it appears that the [SignedBlock](https://github.com/centrifuge/go-substrate-rpc-client/blob/master/types/signed_block.go#L25-L27) only contains the `Extrinsic` not `DynamicExtrinsic`, for which, if I construct a DynamicExtrinsic when sending, I will not be able to parse it as the `Encode` is different. Just want to know if the `DynamicExtrinsic` will be included in the `Block` struct in the coming commits? Thanks!

**Comment by freddyli7** [comment]
hey @cdamian, just saw this PR is ready for review and I assume all changes are finalized.  I noticed that the `Extrinsics` param in the `Block` structure has been changed from `[]Extrinsic` to `[]string`, my question is how should I get the original extrinsic from the Block? I tried to play with this `string` but seems it does not match with the original encoded extrinsic. PS: I got the bytes of my original extrinsic by `Encode()` and I'm trying to fetch it from each Block and see if it's executed.

**Comment by cdamian** [comment]
@freddyli7 The extrinsics that are now returned in the block are no longer decoded. This is due to the fact that decoding an extrinsic now requires metadata and that would've caused too much overhead for a block retrieval. 

If needed, you can now decode extrinsics from a block by using the extrinsic decoder found [here](https://github.com/centrifuge/go-substrate-rpc-client/blob/99d0eb39e55af40d18202ad175a11912856e0a44/registry/factory.go#L212).

Alternatively, if you do not necessarily care for specific block information and only need extrinsics, you can also check the extrinsic retriever found [here](https://github.com/centrifuge/go-substrate-rpc-client/blob/99d0eb39e55af40d18202ad175a11912856e0a44/registry/retriever/extrinsic_retriever.go#L19) and/or check the live test example found [here](https://github.com/centrifuge/go-substrate-rpc-client/blob/99d0eb39e55af40d18202ad175a11912856e0a44/registry/retriever/extrinsic_retriever_live_test.go).

**Pull request merged**
